### ISSUE TITLE
User-can-view-disc-inventory 

### ISSUE THREAD

**Issue by marshall-vogt** [marshall-vogt/ajax-project#1]
## ⚙️ Feature

User can view all PDGA-approved discs, including a flight pattern image and link to external website for purchasing

## 📐 Functionality

User will be prompted to begin building their bag which will link them to the page with all PDGA-approved discs. Discs will be sorted alphabetically by manufacturer. Each disc will include it's name and flight numbers and when the user clicks on the discs, it will expand and show a picture of it's average flight pattern which can be clicked to link user to external website to purchase.

## 🖼️ Wireframes

![Screenshot 2023-08-15 at 10 59 33 AM](https://github.com/marshall-vogt/ajax-project/assets/131848819/963a3fe1-9a51-496a-bdc8-8823aedea336)

<img width="1169" alt="Screenshot 2023-08-15 at 9 42 19 AM" src="https://github.com/marshall-vogt/ajax-project/assets/131848819/522fe57d-e901-49c8-997a-9adb602a49eb">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[class="header-row"]` with logo and title to the HTML.
- [x] Add a `div[data-view="home-page"]` to the HTML and style according to the wireframe.
- [x] Add a `div[data-view="search-page"]` to the HTML.
- [x] Add a 'div[class="discs"]'.
- [x] Add a 'div[class="navbar]' and add necessary elements within navbar.
- [x] Add a button element to "home-page" view that listens for click event and switches to "search-page" view.
- [x] Add some dummy discs with brand header in HTML and style according to the wireframe.
- [x] Check that "home-page" view and "search-page" view look good on both mobile and desktop views.
- [x] Make a request to retrieve disc collection data from API. 
- [x] Define a function for the load event that sorts the response alphabetically by brand name and uses a loop to create a DOM tree for each disc in the data collection and append it to the page.
- [x] Remove the example HTML entries once the disc entries are successfully being appended to the DOM on page load.
- [x] Add an event listener to the "home-page-button" and "search-page-button" and define a callback function that shows the respective view.
- [x] Add styling that changes cursor to hand and expands view of disc when hovering a disc.
- [x] Create an event listener that listens for a click on a disc.
- [x] Define a callback function that blurs "search-page" view and isolates a disc with an image of the average flight pattern.
- [x] Add styling that changes cursor to hand when hovering flight pattern image.
- [x] Add anchor element that wraps the flight pattern image inside the disc modal and update handleDiscClick function to set anchor element 'href' attribute value to the link for the respective disc.
- [x] Clean up unnecessary styling.
- [x] Fix all errors.
