### ISSUE TITLE
User-can-filter-disc-inventory

### ISSUE THREAD

**Issue by marshall-vogt** [marshall-vogt/ajax-project#2]
## ⚙️ Feature

User will be able to narrow down list of disc inventory.

## 📐 Functionality

User can click on a filter button which changes screen to allow user to filter by brand, speed, stability, and category. User can click on a button to either reset filters or to apply the selected filters.

## 🖼️ Wireframes

<img width="1143" alt="Screenshot 2023-08-15 at 9 50 19 AM" src="https://github.com/marshall-vogt/ajax-project/assets/131848819/5c3eefc6-7aca-4680-b222-926c2c7ec05e">
<img width="962" alt="Screenshot 2023-08-15 at 9 49 36 AM" src="https://github.com/marshall-vogt/ajax-project/assets/131848819/7cfb546f-669c-4a5a-a551-c020fabd6185">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add filter page to HTML with drop-down selectors for brand, speed, stability, and category, and buttons to reset or apply filters. Add CSS styling according to wireframe.
- [x] Add button with text content 'Filter' to search page view in HTML to swap view to filter page.
- [x] Add an event listener to 'Filter' button and define a callback function to hide search page and display filter page.
- [x] Add an event listener to 'Reset' button on filter page and define a callback function to reset filters. 
- [x] Add an event listener to 'Apply' button on filter page and define a callback function to remove non-selected items from search page, hide filter page and display search page.
- [x] Remove all unnecessary CSS styling.
- [x] Fix all errors.
