### ISSUE TITLE
User-can-add-discs-to-bag

### ISSUE THREAD

**Issue by marshall-vogt** [marshall-vogt/ajax-project#3]
## ⚙️ Feature

Users will be able to re-create their current bag by saving discs. This will allow the user to identify which discs may fill gaps in their current bag.

## 📐 Functionality

User can click on the 'plus' button in the navigation bar to view their bag. If bag is empty, a message will be displayed. When a disc is selected in the inventory, user can click a button to add the disc to their bag and the page will swap to their bag collection.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="884" alt="Screenshot 2023-08-15 at 9 57 36 AM" src="https://github.com/marshall-vogt/ajax-project/assets/131848819/57034bd6-39ea-4a08-a08b-9db9881bd710">
<img width="911" alt="Screenshot 2023-08-15 at 9 58 05 AM" src="https://github.com/marshall-vogt/ajax-project/assets/131848819/dfd75b64-f162-48fc-b401-f5339bbc7660">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an HTML page to display a user's disc bag and add a button to the disc modal that will allow users to save a disc.
- [x] Create a data file and data model that will store disc information when a user saves the disc to their bag.
- [x] Define a function that will swap to the view of the disc bag and will conditionally check for discs saved in data. If there are discs saved, hide the message "No discs have been added."
- [x] Add an event listener to 'plus' button on the navbar that will utilize the swap view function for user to view their bag.
- [x] Add an event listener to the window object that will listen for a 'beforeunload' event to save discs in the data model to local storage and add a conditional statement to check if there are discs saved and parse data when reloading.
- [x] Define a function to render a disc saved in data to the DOM tree.
- [x] Add an event listener to the document that listens for a 'DOMContentLoaded' event and loops through saved discs and uses the render function for all discs saved in data.
- [x] Add an event listener to the 'Add to Bag' button that saves disc to the data model, renders it to the DOM tree, and swaps view to the user's bag.
